// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjbkqecqgbhbyxloause.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqYmtxZWNxZ2JoYnl4bG9hdXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mzg1MTMsImV4cCI6MjA2ODUxNDUxM30.-mjABupSAvuUp-j13vRuGlHbezEkROHFo3VLGTjckNw";


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
